name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g @vercel/ncc
      - run: npm install
      - run: ncc build index.ts --license licenses.txt
      - name: Commit & push
        run: |
          git config --global user.name 'Build Workflow'
          git config --global user.email 'defaultcommitter@orgflow.io'
          git add --force dist/index.js
          git add --force dist/licenses.txt
          git commit -m "Updates distributables"
          git push