on: [push]

jobs:

  create_stack:
    runs-on: ubuntu-latest
    container: orgflow/cli:1.3.x
    name: Create stack
    steps:
      - run: |
          mkdir /tmp/TestStack1
          git init -b main /tmp/TestStack1
          orgflow stack:create --name=TestStack1 --gitRepoUrl=/tmp/TestStack1 --username=${{ secrets.SALESFORCE_USERNAME }} --password=${{ secrets.SALESFORCE_PASSWORD }} --licenseKey=${{ secrets.ORGFLOW_LICENSEKEY }} --acceptEula

  test_setup:
    runs-on: ubuntu-latest
    name: Test OrgFlow setup action
    needs: create_stack
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up OrgFlow
        uses: ./
        id: setup
        with:
          version: "1.3"
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
          stack-name: TestStack1 # TODO: Make this a variable
        env:
          ORGFLOW_ACCEPTEULA: "true"
      - name: Print installed version
        run: echo "Version ${{ steps.setup.outputs.version }} was installed."

  delete_stack:
    runs-on: ubuntu-latest
    container: orgflow/cli:1.3.x
    name: Delete stack
    needs: [create_stack, test_setup]
    if: ${{ always() }}
    steps:
      - run: |
          orgflow stack:delete --name=TestStack1 --licenseKey=${{ secrets.ORGFLOW_LICENSEKEY }} --acceptEula