on: [push]

jobs:

  create_stack:
    runs-on: ubuntu-latest
    container: orgflow/cli:1.3.x
    name: Create stack
    steps:
      - name: Create temporary stack
        run: |
          mkdir /tmp/$STACKNAME
          git init --bare -b main /tmp/$STACKNAME
          orgflow stack:create --name=$STACKNAME --gitRepoUrl=/tmp/$STACKNAME --username=${{ secrets.SALESFORCE_USERNAME }} --password=${{ secrets.SALESFORCE_PASSWORD }} --licenseKey=${{ secrets.ORGFLOW_LICENSEKEY }} --acceptEula
        env:
          STACKNAME: TestStack_${{github.run_id}}_${{github.run_number}}

  test_setup:
    runs-on: ubuntu-latest
    name: Test setup action
    needs: create_stack
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up OrgFlow
        uses: ./
        id: setup
        with:
          version: "1.3"
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
          stack-name: TestStack_${{github.run_id}}_${{github.run_number}}
        env:
          ORGFLOW_ACCEPTEULA: "true"
      - name: Print outputs
        run: |
          echo "Version: ${{ steps.setup.outputs.version }}"
          echo "Encryption key: ${{ steps.setup.outputs.encryption-key }}"
      - name: Test persisted config
        run: |
          orgflow env:list

  delete_stack:
    runs-on: ubuntu-latest
    container: orgflow/cli:1.3.x
    name: Delete stack
    needs: [create_stack, test_setup]
    if: ${{ always() }}
    steps:
      - name: Delete temporary stack
        run: |
          orgflow stack:delete --name=$STACKNAME --licenseKey=${{ secrets.ORGFLOW_LICENSEKEY }} --acceptEula --noConfirm
        env:
          STACKNAME: TestStack_${{github.run_id}}_${{github.run_number}}
