on: [push]

jobs:
  test_setup_job:
    runs-on: ubuntu-latest
    name: Test OrgFlow setup action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up OrgFlow
        uses: ./
        id: setup
        with:
          version: "1.3"
          license-key: ${{ secrets.ORGFLOW_LICENSEKEY }}
          salesforce-username: ${{ secrets.SALESFORCE_USERNAME }}
          salesforce-password: ${{ secrets.SALESFORCE_PASSWORD }}
          stack-name: ${{ secrets.TestStackName }} # TODO: Make this an organization-level secret
        env:
          ORGFLOW_ACCEPTEULA: "true"
      - name: Print installed version
        run: echo "Version ${{ steps.setup.outputs.version }} was installed."
