on: [push]

jobs:
  test_setup_job:
    runs-on: ubuntu-latest
    name: Test OrgFlow setup action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up OrgFlow
        uses: ./
        id: setup
        with:
          version: "1.3"
          license-key: "3364ACFE-5F05-4D72-AC45-3D0379240F97"
        env:
          ORGFLOW_ACCEPTEULA: "true"
      - name: Print installed version
        run: echo "Version ${{ steps.setup.outputs.version }} was installed."
